### ISSUE TITLE
Cloudflare protection prevents API from being used

### ISSUE THREAD

**Issue by NiGhTTraX** [Quintenps/OverwatchArcade2#13]
First of all, thanks for this project!

I was trying to build a simple website that queries your API and, while it works locally, building the website from Vercel (the NextJS hosting platform) runs into Cloudflare's DDoS protection when calling the API. The API responds with the "wait 5 seconds" HTML page instead of the actual JSON.

As far as I can tell from their [Cloudflare's docs](https://support.cloudflare.com/hc/en-us/articles/200504045-Using-Cloudflare-with-your-API) you can configure a rule for your API routes to disable the interstitial page:

> The Security level controls Cloudflare's basic protection level for the URL pattern. When this feature is set to "I'm Under Attack" either in the Cloudflare settings or in a page rule, each visitor is presented with an interstitial page with a 5 second delay before the request is redirected to its destination. We advise specifying this to anything but "I'm Under Attack" so that there is never a delay applied to API requests.

Would it be possible to look into this?

**Comment by Quintenps** [comment]
Hi,

Thank you for bringing this to my attention. It's probably the user-agent or ASN that's triggering the firewall.
I've added in a rule to exclude /api/* from the firewall. 

Please let me know if this works :)

**Comment by NiGhTTraX** [comment]
Hmm, still doesn't seem to work. I'm querying the `api/overwatch/today` endpoint.

**Comment by Quintenps** [comment]
That's weird. I've turned off another option, could you try again?

**Comment by NiGhTTraX** [comment]
That did the trick! Thank you very much!
