### ISSUE TITLE
On medium (md) sized screens, there are gaps

### ISSUE THREAD

**Issue by nathanhinchey** [Quintenps/OverwatchArcade2#18]
Because the mode cards are in two row divs instead of one, there is an apparent gap after the third image in each row on md size screens. This can be corrected by putting all the cards in a single row div.

This is what it looks like on medium size screens currently:
![current](https://user-images.githubusercontent.com/8533472/111013004-ea440e00-836b-11eb-831b-aa6e39bf1ecb.png)

**Comment by Quintenps** [comment]
Fixed
